apiVersion: apps/v1
kind: Deployment
metadata:
  name: sudoku-frontend
  labels:
    app: sudoku-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sudoku-frontend
  template:
    metadata:
      labels:
        app: sudoku-frontend
    spec:
      containers:
      - name: frontend
        image: prabhath77/sudoku-frontend-final-1:v6
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: sudoku-frontend-service
  labels:
    app: sudoku-frontend
spec:
  selector:
    app: sudoku-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31500
  type: NodePort