# Use an official Node runtime as the base image.
FROM node:16-slim

WORKDIR /app

# Copy only the package files from the slave folder and install dependencies.
COPY slave/package*.json ./
RUN npm install

# Copy your slave code from the slave folder.
COPY slave/slave.js ./

# Copy the shared solver.js from the parent folder.
COPY solver.js  ./

# Run the slave service.
CMD ["node", "slave.js"]